sudo: required

services:
  - docker

# command to run tests
# https://github.com/INCATools/ontology-starter-kit/issues/25
# EMAIL_ARGS='-e obo-ci-reports-all@groups.io'
script:
  - make docker-test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

