sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull
  - git config --global user.email "you@owlsemtest.com"
  - git config --global user.name "Unknown Name"

# command to run tests
# https://github.com/INCATools/ontology-starter-kit/issues/25
# EMAIL_ARGS='-e obo-ci-reports-all@groups.io'
script:
  - docker run -v $PWD/:/work -w /work --rm -ti obolibrary/odkfull make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

