site_name: Ontology Development Kit (ODK)
theme: material
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Initial Setup: InitialSetup.md
repo_url: https://github.com/INCATools/ontology-development-kit

