site_name: Ontology Development Kit (ODK)
theme: material
markdown_extensions:
  - toc:
      permalink: true
nav:
  - InitialSetup.md
  - Creating repo: CreatingRepo.md
  - AddTermToImport.md
  - CreatingRepo.md
  - CreateNewTerm.md
  - DailyWorkflow.md
  - DealWithLargeOntologies.md
  - DeletingAssertedSubClasses.md
  - exts
  - FrequentlyUsedODKCommands.md
  - Installgit.md
  - Create Slim
    - NewSlim.md
    - NewSlimTerm.md
  - MergeTerms.md
  - ObsoleteTerm.md
  - ReleaseArtefacts.md
  - Synonyms.md
  - TaxonRestriction.md
  - TermComments.md
repo_url: https://github.com/INCATools/ontology-development-kit

