name: Build the ODK images and run the tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Create dummy Git user name
        run: git config --global user.name Alice
      - name: Create dummy Git user email
        run: git config --global user.email alice@example.org
      - name: Build the images
        run: make docker-build
      - name: Run the tests
        run: make docker-test
